Handle nil :uses through a polymorphic
When you `includes(:polymorphic => :attr)` and the `:attr` does not have a `:uses`,
this threw an exception.

Reason: Rails 7.2 added a `to_sym` in `reflect_on_association()`,
since `uses[:attr] = nil`, calling `reflect_on_association(nil)` had issues:

```
     Failure/Error: reflection = record.class._reflect_on_association(association)

     NoMethodError:
       undefined method `to_sym' for nil
     # /Users/kbrock/.gem/ruby/3.3.5/gems/activerecord-7.2.2.1/lib/active_record/reflection.rb:127:in `_reflect_on_association'
     # ./lib/active_record/virtual_attributes/virtual_fields.rb:189:in `block in grouped_records'
```

refs:
- https://github.com/rails/rails/issues/5172
- https://github.com/ManageIQ/manageiq-api/pull/1284

Fixes: https://github.com/ManageIQ/manageiq/issues/23518